//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.07 at 10:18:26 AM IST 
//


package com.ankesh.springrestsoap.soap.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactInfoSoapRequest" type="{http://ankesh.com/springrestsoap/soap/dto}contactInfoSoapRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contactInfoSoapRequest"
})
@XmlRootElement(name = "addContactInfoSoapRequest")
public class AddContactInfoSoapRequest {

    @XmlElement(name = "ContactInfoSoapRequest", required = true)
    protected ContactInfoSoapRequest contactInfoSoapRequest;

    /**
     * Gets the value of the contactInfoSoapRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoSoapRequest }
     *     
     */
    public ContactInfoSoapRequest getContactInfoSoapRequest() {
        return contactInfoSoapRequest;
    }

    /**
     * Sets the value of the contactInfoSoapRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoSoapRequest }
     *     
     */
    public void setContactInfoSoapRequest(ContactInfoSoapRequest value) {
        this.contactInfoSoapRequest = value;
    }

}
