//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.07 at 10:18:26 AM IST 
//


package com.ankesh.springrestsoap.soap.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ankesh.springrestsoap.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ankesh.springrestsoap.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddContactInfoSoapResponse }
     * 
     */
    public AddContactInfoSoapResponse createAddContactInfoSoapResponse() {
        return new AddContactInfoSoapResponse();
    }

    /**
     * Create an instance of {@link AddContactInfoSoapRequest }
     * 
     */
    public AddContactInfoSoapRequest createAddContactInfoSoapRequest() {
        return new AddContactInfoSoapRequest();
    }

    /**
     * Create an instance of {@link ContactInfoSoapRequest }
     * 
     */
    public ContactInfoSoapRequest createContactInfoSoapRequest() {
        return new ContactInfoSoapRequest();
    }

}
